import type { Metadata } from "next";
import { Layout } from "@/app/components/Layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex justify-center min-h-screen bg-[#fff]">
        <div className="flex flex-col w-full max-w-[470px] min-h-screen bg-[#F7F6F6]">
          <Layout>{children}</Layout>
        </div>
      </body>
    </html>
  );
}
